export const AuditAction = {
  LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  LOGOUT: 'LOGOUT',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  TECHNICIAN_CREATED: 'TECHNICIAN_CREATED',
  TEMPORARY_CREDENTIAL_REISSUED: 'TEMPORARY_CREDENTIAL_REISSUED',
  USER_UPDATED: 'USER_UPDATED',
  USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_DELETED: 'USER_DELETED',
  MACHINE_CREATED: 'MACHINE_CREATED',
  MACHINE_UPDATED: 'MACHINE_UPDATED',
  MACHINE_DEACTIVATED: 'MACHINE_DEACTIVATED',
  MACHINE_ACTIVATED: 'MACHINE_ACTIVATED',
  MACHINE_DELETED: 'MACHINE_DELETED',
  MACHINE_STATUS_CHANGED: 'MACHINE_STATUS_CHANGED',
  MACHINE_LOG_CREATED: 'MACHINE_LOG_CREATED',
  MACHINE_LOG_UPDATED: 'MACHINE_LOG_UPDATED',
  MACHINE_LOG_DELETED: 'MACHINE_LOG_DELETED',
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditEntity = {
  AUTH: 'AUTH',
  USER: 'USER',
  MACHINE: 'MACHINE',
  MACHINE_LOG: 'MACHINE_LOG',
} as const;

export type AuditEntity = (typeof AuditEntity)[keyof typeof AuditEntity];

export const AUDIT_ACTIONS = Object.values(AuditAction);
export const AUDIT_ENTITIES = Object.values(AuditEntity);
